const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
let cart=stored('ieat.cart',[]), favorites=stored('ieat.favorites',[]), address=stored('ieat.address',''), dishes=[], restaurants=[], user=null, category='all', restaurant=null, authMode='login';
if(!Array.isArray(cart))cart=[];if(!Array.isArray(favorites))favorites=[];
const money=n=>`${n} с.`, modal=$('modal');
async function api(path,data){const res=await fetch('/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});let json;try{json=await res.json()}catch{throw Error('Сервер недоступен')}if(!res.ok)throw Error(json.error||'Не удалось выполнить запрос');return json}
let toastTimer;function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3000)}
function show(content){$('modalContent').innerHTML=content;if(!modal.open)modal.showModal()}
$('closeModal').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()}});
function persistCart(){localStorage.setItem('ieat.cart',JSON.stringify(cart));$('cartCount').textContent=cart.reduce((s,i)=>s+i.qty,0)}
function add(id){const d=dishes.find(d=>d.id===id);if(!d)return;const item=cart.find(i=>i.id===id);if(item&&item.qty>=20)return toast('Максимум 20 порций одного блюда');if(item)item.qty++;else cart.push({id,qty:1});persistCart();toast(`${d.name} в корзине`)}
function renderRestaurants(){ $('restaurantGrid').innerHTML=restaurants.map(r=>`<button class="restaurant ${restaurant===r.id?'selected':''}" data-restaurant="${r.id}" aria-label="Открыть меню ${esc(r.name)}"><div class="restaurant-photo"><img src="${r.image}" alt="${esc(r.name)}" loading="lazy"><span>Бесплатно от 150 с.</span></div><div class="restaurant-body"><h3>${esc(r.name)}</h3><p>${esc(r.cuisine)}</p><div class="restaurant-bottom"><b>★ ${r.rating}</b><span>◷ ${r.time} мин</span></div></div></button>`).join('') }
function renderDishes(){const q=$('searchInput').value.trim().toLocaleLowerCase();let list=dishes.filter(d=>(category==='all'||(category==='favorites'?favorites.includes(d.id):d.category===category))&&(!restaurant||d.restaurant===restaurant)&&(`${d.name} ${d.description}`.toLocaleLowerCase().includes(q)));const sort=$('sortSelect').value;if(sort!=='popular')list.sort((a,b)=>sort==='low'?a.price-b.price:b.price-a.price);$('resultCount').textContent=`${restaurant?restaurants.find(r=>r.id===restaurant).name+' · ':''}Найдено блюд: ${list.length}`;$('resetFilters').hidden=category==='all'&&!restaurant&&!q;$('dishGrid').innerHTML=list.length?list.map(d=>`<article class="dish"><img class="dish-img" src="${d.image}" alt="${esc(d.name)}" loading="lazy"><button class="favorite ${favorites.includes(d.id)?'selected':''}" data-favorite="${d.id}" aria-label="Избранное: ${esc(d.name)}" aria-pressed="${favorites.includes(d.id)}">${favorites.includes(d.id)?'♥':'♡'}</button><div class="dish-body"><h3>${esc(d.name)} <span class="weight">${d.weight} г</span></h3><p>${esc(d.description)}</p><div class="dish-bottom"><b>${d.price} <small>с.</small></b><button class="add-btn" data-add="${d.id}" aria-label="Добавить ${esc(d.name)}">+</button></div></div></article>`).join(''):'<div class="empty">Ничего не найдено. Попробуйте другое название или сбросьте фильтры.</div>'}
function reset(){category='all';restaurant=null;$('searchInput').value='';$('sortSelect').value='popular';document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category==='all'));renderRestaurants();renderDishes()}
document.addEventListener('click',e=>{const addBtn=e.target.closest('[data-add]');if(addBtn)add(Number(addBtn.dataset.add));const f=e.target.closest('[data-favorite]');if(f){const id=Number(f.dataset.favorite);favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('ieat.favorites',JSON.stringify(favorites));renderDishes()}const r=e.target.closest('[data-restaurant]');if(r){restaurant=Number(r.dataset.restaurant);category='all';document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category==='all'));renderRestaurants();renderDishes();$('menu').scrollIntoView()}const c=e.target.closest('[data-category]');if(c){category=c.dataset.category;document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b===c));renderDishes()}});
$('searchInput').oninput=renderDishes;$('sortSelect').onchange=renderDishes;$('resetFilters').onclick=reset;$('allRestaurants').onclick=()=>{reset();$('restaurants').scrollIntoView();toast('Показаны все рестораны')};
$('addressInput').value=typeof address==='string'?address:'';$('addressForm').onsubmit=e=>{e.preventDefault();address=$('addressInput').value.trim();if(address.length<5)return toast('Укажите улицу и номер дома');localStorage.setItem('ieat.address',JSON.stringify(address));$('menu').scrollIntoView();toast('Адрес доставки сохранён')};
function cartRows(){return cart.map(i=>{const d=dishes.find(d=>d.id===i.id);return `<div class="cart-item"><img src="${d.image}" alt=""><div class="item-name">${esc(d.name)}<small>${money(d.price*i.qty)}</small></div><div class="quantity"><button data-quantity="${i.id}" data-delta="-1" aria-label="Уменьшить ${esc(d.name)}">−</button><span>${i.qty}</span><button data-quantity="${i.id}" data-delta="1" aria-label="Увеличить ${esc(d.name)}">+</button></div></div>`}).join('')}
function totals(){const subtotal=cart.reduce((s,i)=>s+dishes.find(d=>d.id===i.id).price*i.qty,0);const delivery=subtotal>=150?0:15;return `<div class="totals"><div><span>Блюда</span><span>${money(subtotal)}</span></div><div><span>Доставка</span><span>${delivery?money(delivery):'Бесплатно'}</span></div><div class="grand"><span>Итого</span><span>${money(subtotal+delivery)}</span></div></div>`}
function openCart(){show(`<h2>Ваша корзина <span class="muted">${cart.reduce((s,i)=>s+i.qty,0)} шт.</span></h2>${cart.length?cartRows()+totals()+'<button id="toCheckout" class="primary full">Перейти к оформлению ↗</button><p>Бесплатная доставка от 150 с.</p>':'<div class="empty">Здесь пока пусто.<br>Самое время найти что-нибудь вкусное.</div><button id="browseMenu" class="primary full">Выбрать блюда</button>'}`);if($('toCheckout'))$('toCheckout').onclick=()=>user?checkout():openAuth('login',checkout);if($('browseMenu'))$('browseMenu').onclick=()=>{modal.close();$('menu').scrollIntoView()}}
$('cartBtn').onclick=openCart;$('modalContent').addEventListener('click',e=>{const q=e.target.closest('[data-quantity]');if(!q)return;const i=cart.find(i=>i.id===Number(q.dataset.quantity));if(!i)return;i.qty+=Number(q.dataset.delta);i.qty=Math.min(20,i.qty);cart=cart.filter(i=>i.qty>0);persistCart();openCart()});
function profileButton(){$('profileBtn').textContent=user?user.name:'Войти'}
function bindForm(id,action){const form=$(id);form.onsubmit=async e=>{e.preventDefault();const submit=form.querySelector('[type=submit]');const err=form.querySelector('.error');err.textContent='';submit.disabled=true;try{await action(Object.fromEntries(new FormData(form)))}catch(error){err.textContent=error.message}finally{if(submit.isConnected)submit.disabled=false}}}
function openAuth(mode='login',after=null){authMode=mode;show(`<h2>${mode==='login'?'С возвращением!':'Приятно познакомиться'}</h2><div class="auth-toggle"><button id="loginTab" class="${mode==='login'?'active':''}">Вход</button><button id="registerTab" class="${mode==='register'?'active':''}">Регистрация</button></div><form id="authForm" class="form">${mode==='register'?'<label>Ваше имя<input name="name" required minlength="2" maxlength="80" autocomplete="name"></label>':''}<label>Email<input name="email" type="email" required autocomplete="email"></label><label>Пароль<input name="password" type="password" required minlength="8" maxlength="128" autocomplete="${mode==='login'?'current-password':'new-password'}"></label><p class="error" role="alert"></p><button type="submit" class="primary">${mode==='login'?'Войти':'Создать аккаунт'}</button></form><p>Пароль — минимум 8 символов. Данные хранятся на сервере приложения.</p>`);$('loginTab').onclick=()=>openAuth('login',after);$('registerTab').onclick=()=>openAuth('register',after);bindForm('authForm',async data=>{const result=await api(mode==='login'?'login':'register',data);user=result.user;profileButton();if(after)after();else{modal.close();toast('Добро пожаловать, '+user.name+'!')}})}
$('profileBtn').onclick=()=>user?openProfile():openAuth();
function checkout(){if(!cart.length)return openCart();show(`<h2>Оформление заказа</h2><p>Тестовый заказ · оплата не списывается</p>${totals()}<form id="checkoutForm" class="form"><label>Адрес в Худжанде<input name="address" required minlength="5" maxlength="300" autocomplete="street-address" value="${esc(address||user.address)}" placeholder="Улица, дом, квартира"></label><label>Телефон<input name="phone" type="tel" required pattern="\\+?[0-9\\s()\\-]{9,20}" value="${esc(user.phone)}" placeholder="+992 900000000" autocomplete="tel"></label><label>Комментарий курьеру<textarea name="note" maxlength="500" placeholder="Подъезд, этаж или пожелания"></textarea></label><label>Способ оплаты<input value="Наличными при получении (тестовый режим)" readonly></label><p class="error" role="alert"></p><button type="submit" class="primary">Подтвердить тестовый заказ</button></form>`);bindForm('checkoutForm',async data=>{const result=await api('orders',{...data,items:cart.map(i=>({id:i.id,qty:i.qty}))});address=data.address;localStorage.setItem('ieat.address',JSON.stringify(address));$('addressInput').value=address;cart=[];persistCart();show(`<div class="success"><div class="success-icon">✓</div><h2>Заказ №${result.id} сохранён!</h2><p>Сумма: ${money(result.total)}<br>Статус: ${result.status}</p><p>Это тестовый заказ. Ресторан и курьер не получат его.</p><button id="viewOrders" class="primary full">Посмотреть мои заказы</button></div>`);$('viewOrders').onclick=openOrders})}
function openProfile(){show(`<h2>Мой профиль</h2><p>${esc(user.email)}</p><form id="profileForm" class="form"><label>Имя<input name="name" value="${esc(user.name)}" required minlength="2" maxlength="80"></label><label>Телефон<input name="phone" type="tel" value="${esc(user.phone)}" required placeholder="+992 900000000"></label><label>Адрес<input name="address" value="${esc(user.address)}" required minlength="5" maxlength="300"></label><p class="error" role="alert"></p><button type="submit" class="primary">Сохранить изменения</button></form><div class="profile-links"><button id="myOrders" class="text-btn">Мои заказы ↗</button><button id="logout" class="text-btn">Выйти</button></div>`);bindForm('profileForm',async data=>{user=(await api('profile',data)).user;profileButton();toast('Профиль сохранён')});$('myOrders').onclick=openOrders;$('logout').onclick=async()=>{try{await api('logout',{});user=null;profileButton();modal.close();toast('Вы вышли из аккаунта')}catch(e){toast(e.message)}}}
async function openOrders(){show('<h2>Мои заказы</h2><p>Загружаем историю…</p>');try{const orders=await api('orders');show(`<h2>Мои заказы</h2>${orders.length?orders.map(o=>`<article class="order"><div class="order-head"><b>Заказ №${o.id}</b><span class="badge">${esc(o.status)}</span></div><p>${esc(new Date(o.created.replace(' ','T')+'Z').toLocaleString('ru-RU'))}<br>${o.items.map(i=>`${esc(i.name)} × ${i.qty}`).join(', ')}<br>${esc(o.address)}</p><b>${money(o.total)}</b><div><button class="text-btn" data-repeat="${o.id}">Повторить</button>${o.status==='Принят'?`<button class="text-btn" data-cancel="${o.id}">Отменить заказ</button>`:''}</div></article>`).join(''):'<div class="empty">У вас пока нет заказов</div>'}`);document.querySelectorAll('[data-repeat]').forEach(b=>b.onclick=()=>{const o=orders.find(o=>o.id===Number(b.dataset.repeat));cart=o.items.map(i=>({id:i.id,qty:i.qty}));persistCart();openCart()});document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('orders/cancel',{id:Number(b.dataset.cancel)});await openOrders();toast('Заказ отменён')}catch(e){toast(e.message);b.disabled=false}})}catch(e){show(`<h2>Мои заказы</h2><p class="error">${esc(e.message)}</p>`)}}
$('partnerBtn').onclick=()=>{show('<h2>Давайте работать вместе</h2><p>Заявка сохранится в базе этого тестового сервиса.</p><form id="partnerForm" class="form"><label>Название ресторана<input name="restaurant" required maxlength="150"></label><label>Ваше имя<input name="name" required maxlength="150"></label><label>Телефон<input name="phone" type="tel" required maxlength="20"></label><p class="error" role="alert"></p><button type="submit" class="primary">Отправить заявку</button></form>');bindForm('partnerForm',async data=>{await api('partners',data);show('<div class="success"><div class="success-icon">✓</div><h2>Заявка сохранена</h2><p>Данные сохранены в тестовом сервисе. Автоматической отправки менеджеру нет.</p></div>')})};
const info={support:['Поддержка','Если возникла проблема с тестовым заказом, откройте кабинет и отмените заказ или оформите его заново. Внешняя служба поддержки пока не подключена.'],terms:['Условия сервиса','iEat работает в тестовом режиме. Меню и рестораны демонстрационные. Заказы не передаются ресторанам, доставка не выполняется, платежи не списываются.'],privacy:['Конфиденциальность','Аккаунт, контактные данные и заказы хранятся в SQLite на сервере. Пароли хранятся в виде хешей, сессия — в HttpOnly cookie. Корзина и избранное сохраняются в браузере. Не вводите чувствительные данные в тестовом сервисе.']};document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>{const [title,text]=info[b.dataset.info];show(`<h2>${title}</h2><p>${text}</p>`) });
async function init(){try{const [catalog,me]=await Promise.all([api('catalog'),api('me')]);dishes=catalog.dishes;restaurants=catalog.restaurants;user=me.user;cart=cart.filter(i=>i&&dishes.some(d=>d.id===i.id)&&Number.isInteger(i.qty)&&i.qty>0&&i.qty<=20);persistCart();profileButton();renderRestaurants();renderDishes()}catch(e){$('dishGrid').innerHTML=`<div class="empty">${esc(e.message)}. <button id="retryInit" class="text-btn">Повторить</button></div>`;$('retryInit').onclick=init;toast('Не удалось загрузить меню')}}init();
