const restaurants=[['Burger Lab','Бургеры · Фастфуд','https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=600&q=85','4.9'],['Pizza Casa','Пицца · Итальянская','https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=85','4.8'],['Sushi Time','Суши · Японская','https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=85','4.9'],['Wok House','Азиатская · Лапша','https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=85','4.7']];
const dishes=[['BBQ Burger','Сочный бургер с соусом BBQ',25,'burger','https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=85'],['Pepperoni','Пепперони, моцарелла, томаты',50,'pizza','https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=85'],['California Roll','Лосось, авокадо, сливочный сыр',40,'sushi','https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=85'],['Wok Chicken','Курица, овощи и лапша',36,'asian','https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=600&q=85'],['Cheese Burger','Двойной сыр и говядина',29,'burger','https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=85'],['Margherita','Томаты, моцарелла, базилик',43,'pizza','https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=85'],['Tiramisu','Классический итальянский десерт',25,'dessert','https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=85'],['Ramen','Японский рамен с курицей',38,'asian','https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=85']];
let cart=[];
const restaurantGrid=document.getElementById('restaurantGrid');
restaurantGrid.innerHTML=restaurants.map(r=>`<article class="restaurant"><img class="restaurant-img" src="${r[2]}" alt="${r[0]}"><div class="restaurant-body"><h3>${r[0]}</h3><p>${r[1]}</p><div class="rating">⭐ ${r[3]} · 25–40 мин</div></div></article>`).join('');
function renderDishes(category='all'){const list=category==='all'?dishes:dishes.filter(d=>d[3]===category);document.getElementById('dishGrid').innerHTML=list.map(d=>`<article class="dish"><img class="dish-img" src="${d[4]}" alt="${d[0]}"><div class="dish-info"><h3>${d[0]}</h3><p>${d[1]}</p><div class="dish-bottom"><span class="price">${d[2]} сомони</span><button class="add" onclick="addToCart('${d[0]}',${d[2]})">+</button></div></div></article>`).join('')}
renderDishes();
document.querySelectorAll('.cat').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.cat.active').classList.remove('active');btn.classList.add('active');renderDishes(btn.dataset.category)}));
window.addToCart=(name,price)=>{const item=cart.find(x=>x.name===name);if(item)item.qty++;else cart.push({name,price,qty:1});updateCart()};
function updateCart(){document.getElementById('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);document.getElementById('cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-item"><span>${x.name} × ${x.qty}<br><b>${x.price*x.qty} сомони</b></span><button class="remove-item" data-index="${i}" type="button">Удалить</button></div>`).join(''):'<p>Корзина пока пуста.</p>';document.querySelectorAll('.remove-item').forEach(button=>button.onclick=()=>{cart.splice(Number(button.dataset.index),1);updateCart()});document.getElementById('cartTotal').textContent=cart.reduce((s,x)=>s+x.price*x.qty,0)+' сомони'}
document.getElementById('cartBtn').onclick=()=>document.getElementById('cartModal').classList.add('show');
document.getElementById('closeCart').onclick=()=>document.getElementById('cartModal').classList.remove('show');
document.getElementById('checkoutBtn').onclick=()=>{if(!cart.length){alert('Добавьте блюда в корзину.');return}const orders=JSON.parse(localStorage.getItem('iEatOrders')||'[]');orders.unshift({date:new Date().toLocaleString('ru-RU'),items:cart.map(item=>`${item.name} × ${item.qty}`),total:cart.reduce((s,x)=>s+x.price*x.qty,0)});localStorage.setItem('iEatOrders',JSON.stringify(orders));cart=[];updateCart();document.getElementById('cartModal').classList.remove('show');alert('Заказ принят! Он сохранён в истории профиля.')};
document.getElementById('findBtn').onclick=()=>alert(document.getElementById('addressInput').value?'Ищем рестораны по адресу: '+document.getElementById('addressInput').value:'Введите адрес доставки');
document.getElementById('searchBtn').onclick=()=>document.getElementById('addressInput').focus();
const loginModal=document.getElementById('loginModal'),loginBtn=document.getElementById('loginBtn'),loginForm=document.getElementById('loginForm'),loginError=document.getElementById('loginError'),profileModal=document.getElementById('profileModal'),profileForm=document.getElementById('profileForm');
function getProfile(){return JSON.parse(localStorage.getItem('iEatProfile')||'null')}
function updateLoginButton(){const profile=getProfile();loginBtn.textContent=profile?`Профиль (${profile.name})`:'Войти';loginBtn.setAttribute('aria-label',profile?'Открыть профиль':'Войти в аккаунт')}
loginBtn.onclick=()=>{if(getProfile())openProfile();else{loginError.textContent='';loginForm.reset();loginModal.classList.add('show');document.getElementById('loginName').focus()}};
document.getElementById('closeLogin').onclick=()=>loginModal.classList.remove('show');
loginForm.onsubmit=event=>{event.preventDefault();const password=document.getElementById('loginPassword').value;if(password.length<6){loginError.textContent='Пароль должен содержать минимум 6 символов.';return}localStorage.setItem('iEatProfile',JSON.stringify({name:document.getElementById('loginName').value.trim(),email:document.getElementById('loginEmail').value.trim(),phone:document.getElementById('loginPhone').value.trim(),address:document.getElementById('loginAddress').value.trim()}));updateLoginButton();loginModal.classList.remove('show')};
function openProfile(){const profile=getProfile();if(!profile)return;document.getElementById('profileSummaryName').textContent=profile.name;document.getElementById('profileSummaryEmail').textContent=profile.email;document.getElementById('profileName').value=profile.name;document.getElementById('profilePhone').value=profile.phone;document.getElementById('profileAddress').value=profile.address;const orders=JSON.parse(localStorage.getItem('iEatOrders')||'[]');document.getElementById('orderHistory').innerHTML=orders.length?orders.map(order=>`<div class="order-row"><span>${order.date}<br>${order.items.join(', ')}</span><b>${order.total} сомони</b></div>`).join(''):'<p class="orders-empty">Заказов пока нет.</p>';profileModal.classList.add('show')}
document.getElementById('closeProfile').onclick=()=>profileModal.classList.remove('show');
profileForm.onsubmit=event=>{event.preventDefault();const profile=getProfile();profile.name=document.getElementById('profileName').value.trim();profile.phone=document.getElementById('profilePhone').value.trim();profile.address=document.getElementById('profileAddress').value.trim();localStorage.setItem('iEatProfile',JSON.stringify(profile));updateLoginButton();openProfile()};
document.getElementById('logoutBtn').onclick=()=>{localStorage.removeItem('iEatProfile');profileModal.classList.remove('show');updateLoginButton()};
updateLoginButton();
